// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFpaHn58NWiR90pPWJsEAOPhd-2oiha2Y',
    appId: '1:1086627119682:web:85235bbffc017f0d76a3db',
    messagingSenderId: '1086627119682',
    projectId: 'packages-demo-119b7',
    authDomain: 'packages-demo-119b7.firebaseapp.com',
    storageBucket: 'packages-demo-119b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP2BlxWwlm0GI4PZHZRl-NAf6fiG1IhJY',
    appId: '1:1086627119682:android:3aecab4a98fe263176a3db',
    messagingSenderId: '1086627119682',
    projectId: 'packages-demo-119b7',
    storageBucket: 'packages-demo-119b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sl8UO3b0YzZG-x_gbim52EpKzl1aVoU',
    appId: '1:1086627119682:ios:c6b466bf06bbdce976a3db',
    messagingSenderId: '1086627119682',
    projectId: 'packages-demo-119b7',
    storageBucket: 'packages-demo-119b7.appspot.com',
    androidClientId: '1086627119682-3a0smf3p0pcaf60pl2vd88da7afb5bq1.apps.googleusercontent.com',
    iosClientId: '1086627119682-cpa5vejcfs9voe3bp0ltf9kdstkc375u.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthHandlerDemo',
  );
}
